### ISSUE TITLE
More gamemodes

### ISSUE THREAD

**Issue by Spannner** [neontribe/untangled-game#155]
I think it's time for more gamemodes. We're not under any pressure to finish it in a week, so let's do as many as we can.

I'm thinking of things like a splatoon mode, a hunger games mode, deathmatch, etc.

We'll need to modify the menu for this and also allow multiple servers with specific gamemode types.

**Comment by Hoolean** [comment]
On a different engine this year, so closing the issue. We're leaving 2017 in the source, so feel free to keep at it :)
