### ISSUE TITLE
Node group allegedly doesn't exist

### ISSUE THREAD

**Issue by Spannner** [neontribe/untangled-game#173]
Seemingly randomly, the node server that the client is attempting to join does not exist.

**Comment by whizzer0** [comment]
Is this the "Group [hostname] does not found" error? It seems to have been fixed.

**Comment by Spannner** [comment]
I'm sure I remember having it recently, but yes this is the error I'm talking about.
If it has been fixed, what was wrong?

**Comment by whizzer0** [comment]
It varies by branch, but master does not appear to have the issue.
